arch:
  - ppc64le
  - s390x
  - arm64
os: linux
dist: focal
language: python
python: "3.8"

allow_failures:
  - s390x

branches:
  only:
  - master

before_install:
  - sudo apt-get --yes install libgeos-dev
  - pip install numpy cython

install:
  - python setup.py build_ext --inplace
  - pip install . --no-deps --no-build-isolation

script:
  - pytest --doctest-modules
