language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - "TRAVIS_SPEEDUP_OPTS=--with-speedups"
  - "TRAVIS_SPEEDUP_OPTS="

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgeos-dev python-numpy
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
  - pip install --install-option="--no-cython-compile" cython
  - pip install -r requirements-dev.txt

install:
  - pip install -e .

script: "py.test tests ${TRAVIS_SPEEDUP_OPTS}"

notifications:
    email: false
