language: minimal

matrix:
  include:
  - os: linux  # 2015
    env: DEPS="python=3.5 numpy=1.10 geos=3.5"
  - os: linux  # 2017
    env: DEPS="python=3.6 numpy=1.13 geos=3.6"
  - os: linux  # now
    env: DEPS="python=3.7 numpy geos"
  - os: osx
    env: DEPS="python=3.7 numpy geos"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda:$HOME/miniconda/bin:$PATH"
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r;
  - conda update --yes conda;
  - conda config --set changeps1 no --set restore_free_channel true;
  - conda create -n testenv --yes pytest $DEPS;
  - conda activate testenv;
  - conda --version ; python --version ; pip --version;
  - python setup.py build_ext --inplace
  - pip install . --no-deps

script: pytest --doctest-modules
