language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgeos-dev
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
  - pip install cython numpy

install:
  - python setup.py build

script: "python setup.py test"

notifications:
    email: false
