language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: "2.7"
      env:
        - SPEEDUPS=1
        - NUMPY=1
    - python: "2.7"
      env:
        - SPEEDUPS=0
        - NUMPY=1
    - python: "2.7"
      env:
        - SPEEDUPS=0
        - NUMPY=0
    - python: "3.5"
      env:
        - SPEEDUPS=1
        - NUMPY=1
    - python: "3.5"
      env:
        - SPEEDUPS=0
        - NUMPY=1
    - python: "3.6"
      env:
        - SPEEDUPS=1
        - NUMPY=1
    - python: "3.6"
      env:
        - SPEEDUPS=0
        - NUMPY=1
    - python: "3.6"
      env:
        - SPEEDUPS=0
        - NUMPY=0
    - python: "3.7"
      env:
        - SPEEDUPS=1
        - NUMPY=1
    - python: "3.7"
      env:
        - SPEEDUPS=0
        - NUMPY=1
    - python: "3.7"
      env:
        - SPEEDUPS=0
        - NUMPY=0

addons:
  apt:
    packages:
      - libgeos-dev

before_install:
  - python -m pip install -U pip
  - python -m pip --version
  # if building with speedups install cython
  - if [ "$SPEEDUPS" == "1" ]; then pip install --install-option="--no-cython-compile" cython; fi
  # if testing without numpy explicitly remove it
  - if [ "$NUMPY" == "0" ]; then pip uninstall --yes numpy; fi
  # convert SPEEDUPS to --with-speedups/--without-speedups
  - if [ "$SPEEDUPS" == "1" ]; then SPEEDUPS_FLAG=--with-speedups; else SPEEDUPS_FLAG=--without-speedups; fi

install:
  - python -m pip install --upgrade coveralls pytest-cov pytest>=3.8
  - python -m pip install -e .[all]

script:
  - python -m pytest --cov shapely --cov-report term-missing "${SPEEDUPS_FLAG}"

after_success:
  - coveralls || echo "!! intermittent coveralls failure"

notifications:
    email: false
