---
image: Visual Studio 2019
platform: x64

environment:
  global:
    COMPILER: msvc2019

  matrix:
    # Interleave PYTHON, ARCH and GEOS_VERSION
    - PYTHON: "C:\\Python35-x64"
      ARCH: x64
      GEOS_VERSION: "3.5.2"
    - PYTHON: "C:\\Python36"
      ARCH: x86
      GEOS_VERSION: "3.6.4"
    - PYTHON: "C:\\Python37-x64"
      ARCH: x64
      GEOS_VERSION: "3.7.3"
    - PYTHON: "C:\\Python38"
      ARCH: x86
      GEOS_VERSION: "3.8.1"
    - PYTHON: "C:\\Python39-x64"
      ARCH: x64
      GEOS_VERSION: "3.9.0beta2"


install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

build: false  # disable automatic build
build_script:
  - set GEOS_INSTALL=C:\projects\deps\geos-%GEOS_VERSION%-%COMPILER%-%ARCH%
  - set CYTHONPF=C:\\projects\\deps\\geos-%GEOS_VERSION%-%COMPILER%-%ARCH%
  - set GEOS_LIBRARY_PATH=%GEOS_INSTALL%\bin\geos_c.dll

  - ps: 'Write-Host "Configuring MSVC compiler $env:COMPILER" -ForegroundColor Magenta'
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%

  - ps: 'Write-Host "Configuring PATH with $env:PYTHON and $env:GEOS_INSTALL\bin" -ForegroundColor Magenta'
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%GEOS_INSTALL%\bin;%PATH%
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install --upgrade wheel

  - ps: 'Write-Host "Checking GEOS build $env:GEOS_INSTALL" -ForegroundColor Magenta'
  - if not exist C:\projects\deps mkdir C:\projects\deps
  - call %APPVEYOR_BUILD_FOLDER%\ci\install_geos.cmd

  - ps: 'Write-Host "Checking geos_c.dll" -ForegroundColor Magenta'
  - python -c "import sys; print('Python ' + sys.version)"
  - python -c "import ctypes, os; print(ctypes.CDLL(os.environ['GEOS_LIBRARY_PATH']))"

  - ps: 'Write-Host "Building extension" -ForegroundColor Magenta'
  - cd %APPVEYOR_BUILD_FOLDER%
  - pip install -r requirements-dev.txt
  - python setup.py build_ext --inplace -I%CYTHONPF%\\include -lgeos_c -L%CYTHONPF%\\lib

  - ps: 'Write-Host "Running pytest" -ForegroundColor Magenta'
  - pytest
  - python -c "import shapely; print(shapely.__version__)"
  - python -c "from shapely.geos import geos_version_string; print(geos_version_string)"
  - python -c "from shapely import speedups; assert speedups.enabled"


cache:
  - C:\projects\deps -> %APPVEYOR_BUILD_FOLDER%\ci\install_geos.cmd
