environment:
  matrix:
    - PYTHON: "C:\\Miniconda3"
      DEPS: "numpy geos"

    - PYTHON: "C:\\Miniconda3-x64"
      DEPS: "numpy geos"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION%"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

  # Prepend to the PATH of this build
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%CONDA_ROOT%\\Library\\bin;%PATH%"

  # Install dependencies
  - conda update --yes conda
  - conda create -n testenv --yes %DEPS% pytest
  - activate testenv


build: false

before_test:
  - "set GEOS_LIBRARY_PATH=%CONDA_PREFIX%\\Library\\lib"
  - "set GEOS_INCLUDE_PATH=%CONDA_PREFIX%\\Library\\include"
  - "%CMD_IN_ENV% python setup.py build_ext --inplace"

test_script:
  - "%CMD_IN_ENV% pytest"
