name: pygeos
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py37_0
  - asn1crypto=0.24.0=py37_0
  - babel=2.7.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1
  - cryptography=2.7=py37h1ba5d50_0
  - docutils=0.14=py37_0
  - geos=3.7.1=he6710b0_0
  - idna=2.8=py37_0
  - imagesize=1.1.0=py37_0
  - intel-openmp=2019.4=243
  - jinja2=2.10.1=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - numpydoc=0.9.1=py_0
  - openssl=1.1.1c=h7b6447c_1
  - packaging=19.0=py37_0
  - pip=19.1.1=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h0371630_0
  - pytz=2019.1=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - snowballstemmer=1.9.0=py_0
  - sphinx=2.1.2=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
