name: Test

on: [push, pull_request]

jobs:
  Test:
    name: ${{ matrix.os }}-${{ matrix.architecture }} Py${{ matrix.python }} GEOS ${{ matrix.geos }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        architecture: [x64]
        geos: [3.6.4, 3.7.3, 3.8.1, 3.9.1, 3.10.0, main]
        include:
          # 2017
          - python: 3.6
            geos: 3.6.4
            numpy: 1.13.3
          # 2018
          - python: 3.7
            geos: 3.7.3
            numpy: 1.15.4
          # 2019
          - python: 3.8
            geos: 3.8.1
            numpy: 1.17.5
          # 2020
          - python: 3.9
            geos: 3.9.1
            numpy: 1.19.5
          # 2021
          - python: "3.10"
            geos: 3.10.0
            numpy: 1.21.3
          # dev
          - python: "3.10"
            geos: main
          # enable two 32-bit windows builds:
          - os: windows-2019
            architecture: x86
            python: 3.6
            geos: 3.6.4
            numpy: 1.13.3
          - os: windows-2019
            architecture: x86
            python: 3.9
            geos: 3.10.0
            numpy: 1.19.5

    env:
      GEOS_VERSION: ${{ matrix.geos }}
      GEOS_VERSION_SPEC: ${{ matrix.geos }}
      GEOS_INSTALL: ${{ github.workspace }}/geosinstall/geos-${{ matrix.geos }}
      GEOS_BUILD: ${{ github.workspace }}/geosbuild

    steps:
      - name: Correct slashes in GEOS_INSTALL (Windows)
        run: |
          echo 'GEOS_INSTALL=${{ github.workspace }}\geosinstall\geos-${{ matrix.geos }}' >> $GITHUB_ENV
          echo 'GEOS_BUILD=${{ github.workspace }}\geosbuild' >> $GITHUB_ENV
        if: ${{ matrix.os == 'windows-2019' }}

      - name: Checkout PyGEOS
        uses: actions/checkout@v2

      - name: Checkout GEOS (main)
        uses: actions/checkout@v2
        with:
          repository: libgeos/geos
          ref: main
          path: ${{ env.GEOS_BUILD }}
        if: ${{ matrix.geos == 'main' }}

      - name: Put the latest commit hash in the cache token
        run: |
          echo "GEOS_VERSION_SPEC=$(git rev-parse HEAD)" >> $GITHUB_ENV
        working-directory: ${{ env.GEOS_BUILD }}
        if: ${{ matrix.geos == 'main' }}

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.architecture }}

      - name: Cache GEOS and pip packages
        uses: actions/cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.architecture }}-geos-${{ env.GEOS_VERSION_SPEC }}-${{ hashFiles('ci/install_geos.sh') }}
          path: |
            ~/.cache/pip
            ${{ github.workspace }}/geosinstall

      - name: Activate MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture }}
        if: ${{ matrix.os == 'windows-2019' }}

      - name: Install GEOS
        run: |
          bash ci/install_geos.sh

      - name: Install python dependencies
        run: |
          python -m pip install --disable-pip-version-check --upgrade pip
          pip install --upgrade wheel setuptools
          if [ "$GEOS_VERSION" = "main" ]; then
            pip install --upgrade --pre Cython numpy pytest;
          else
            pip install --upgrade Cython numpy==${{ matrix.numpy }} pytest;
          fi
          pip list

      - name: Set environment variables (Linux)
        run: |
          echo "${{ env.GEOS_INSTALL }}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${{ env.GEOS_INSTALL }}/lib" >> $GITHUB_ENV
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Set environment variables (OSX)
        run: |
          echo "${{ env.GEOS_INSTALL }}/bin" >> $GITHUB_PATH
          echo "LDFLAGS=-Wl,-rpath,${{ env.GEOS_INSTALL }}/lib" >> $GITHUB_ENV
        if: ${{ matrix.os == 'macos-latest' }}

      # Windows requires special treatment:
      # - geos-config does not exist, so we specify include and library paths
      # - Python >=3.8 ignores the PATH for finding DLLs, so we copy them into the package 
      - name: Set environment variables + copy DLLs (Windows)
        run: |
          cp geosinstall/geos-${{ matrix.geos }}/bin/*.dll pygeos
          echo 'GEOS_LIBRARY_PATH=${{ env.GEOS_INSTALL }}\lib' >> $GITHUB_ENV
          echo 'GEOS_INCLUDE_PATH=${{ env.GEOS_INSTALL }}\include' >> $GITHUB_ENV
        if: ${{ matrix.os == 'windows-2019' }}

      - name: Build PyGEOS
        run: python setup.py build_ext --inplace

      - name: Run tests
        continue-on-error: ${{ matrix.geos == 'main' }}
        run: pytest pygeos

      # Only run doctests on 1 runner (because of typographic differences in doctest results)
      - name: Run doctests
        run: pytest --doctest-modules pygeos --ignore=pygeos/tests
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.10.0' }}
