name: Linux

on: [push, pull_request]

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} (GEOS ${{ matrix.geos }}, numpy ${{ matrix.numpy || 'latest' }})
    # runs-on: ubuntu-latest
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2015
          - python: 3.5
            geos: 3.5.2
            numpy: 1.10.4
          # 2017
          - python: 3.6
            geos: 3.6.4
            numpy: 1.13.3
          # 2018
          - python: 3.7
            geos: 3.7.3
            numpy: 1.15.4
          # 2019
          - python: 3.8
            geos: 3.8.1
            numpy: 1.17.5
          # 2020
          - python: 3.9
            geos: 3.9.1
            numpy: 1.19.5
          # dev
          - python: 3.9
            geos: master

    env:
      GEOS_VERSION: ${{ matrix.geos }}
      GEOS_INSTALL: ${{ github.workspace }}/geosinstall/geos-${{ matrix.geos }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache GEOS and pip packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-geos-${{ matrix.geos }}
          path: |
            ~/.cache/pip
            ${{ github.workspace }}/geosinstall

      - name: Install GEOS
        shell: bash
        run: |
          ./ci/install_geos.sh
          cd ${{ github.workspace }}

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip
          pip install --upgrade wheel
          if [ "$GEOS_VERSION" = "master" ]; then
            pip install --upgrade --pre Cython numpy pytest;
          else
            pip install --upgrade Cython numpy==${{ matrix.numpy }} pytest;
          fi
          pip list

      - name: Set environment variables
        shell: bash
        run: |
          echo "LD_LIBRARY_PATH=$GEOS_INSTALL/lib" >> $GITHUB_ENV
          echo $GEOS_INSTALL/bin >> $GITHUB_PATH

      - name: Build PyGEOS
        shell: bash
        run: |
          python setup.py build_ext --inplace
          pip install --no-deps -e .

      - name: Run tests
        shell: bash
        continue-on-error: ${{ matrix.geos == 'master' }}
        run: |
          pytest
