name: Test using Conda environments

on: [push, pull_request]

jobs:
  TestConda:
    name: ${{ matrix.os }} - Python ${{ matrix.python }} (GEOS ${{ matrix.geos || 'latest' }}, numpy ${{ matrix.numpy || 'latest' }}, conda ${{ matrix.channel || 'defaults' }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8]
        channel: ['']
        include:
          - os: ubuntu-latest
            python: 3.8
            channel: conda-forge
          - os: macos-latest
            python: 3.6
            geos: 3.6
            numpy: 1.13
          - os: macos-latest
            python: 3.7
            geos: 3.7
            numpy: 1.15
          - os: macos-latest
            python: 3.8
            geos: 3.8
            numpy: 1.17
          - os: macos-latest
            python: 3.8
            channel: defaults
          - os: macos-latest
            python: 3.8
            channel: conda-forge
          - os: windows-latest
            python: 3.6
            geos: 3.6
            numpy: 1.13
          - os: windows-latest
            python: 3.7
            geos: 3.7
            numpy: 1.15
          - os: windows-latest
            python: 3.8
            geos: 3.8
            numpy: 1.17
          - os: windows-latest
            python: 3.8
            channel: defaults
          - os: windows-latest
            python: 3.8
            channel: conda-forge

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: false
          conda-channels: ${{ matrix.channel }}

      - name: Setup Environment
        shell: bash
        run: |
          conda create --name test python=${{ matrix.python }} pytest geos=${{ matrix.geos || '' }} numpy=${{ matrix.numpy || '' }}
          source activate test
          python -V
          conda info
          conda list

      # set GEOS paths for Windows
      - name: Set GEOS library / include folders
        shell: bash
        if: contains(matrix.os, 'windows')
        run: |
          echo "GEOS_LIBRARY_PATH=C:\\Miniconda\\envs\\test\\Library\\lib" >> $GITHUB_ENV
          echo "GEOS_INCLUDE_PATH=C:\\Miniconda\\envs\\test\\Library\\include" >> $GITHUB_ENV

      - name: Build and install PyGEOS
        shell: bash
        run: |
          source activate test
          pip install -e . --no-deps -v

      - name: Run tests
        shell: bash
        continue-on-error: ${{ matrix.channel == 'conda-forge' }}
        run: |
          source activate test
          pytest --doctest-modules
